### ISSUE TITLE
clarification: what versions of GMP (+MPIR?) are supported

### ISSUE THREAD

**Issue by GitMensch** [nakatamaho/gmpxx_mkII#2]
This information is currently missing in the README, but seems quite important.

As far as I understand this all goes down to gmp.h (MPIR generates that in gmpcompat as well) providing the necessary definitions, but an "official" statement on the version needed would be good - even if it gets down to "tested with GMP 6.2.1, it may not work with older versions or MPIR (we welcome test results with other versions").

.. actually I've tested trhe compilation part with MPIR, it seems that "MPIR master March 2018 or newer" is the answer to that (there is no newer release than MPIR 3.0.0

**Comment by nakatamaho** [comment]
Thank you very much, I update the README.md

**Comment by GitMensch** [comment]
Have you tested older GMP versions or is this a possible open task?

**Comment by nakatamaho** [comment]
No, I have never tested it. I welcome patches of course.
